# Generated by Django 4.0.5 on 2022-06-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posts',
        ),
    ]
