# Generated by Django 4.0.5 on 2022-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_profile',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
