# Generated by Django 4.0.5 on 2022-06-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_profile_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_profile',
        ),
    ]
