# Generated by Django 4.0.5 on 2022-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_rename_comment_comment_body_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default-img.jpg', upload_to='images/'),
        ),
    ]
