# Generated by Django 4.0.5 on 2022-06-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static/images/default-img.jpg', upload_to='images/'),
        ),
    ]
